### ISSUE TITLE
[Bug]: Brightness And Volume gesture

### ISSUE THREAD

**Issue by Vincracked** [NoCrypt/migu#15]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

v5.3.8

### What operating system version are you using?

Android

### Expected Behavior

Volume and brightness gesture should only work while sliding vertically.

### Actual Behavior

Volume and brightness gesture works even while sliding horizontally . Also how can I disable the brightness and volume gesture?

**Comment by NoCrypt** [comment]
Done https://github.com/NoCrypt/migu/commit/3bb3c7436f2a01a5200b7a005011cc62224196b9

**Comment by Vincracked** [comment]
Is it fixed?

**Comment by NoCrypt** [comment]
yes
