### ISSUE TITLE
[Feature Request]: MAL integration

### ISSUE THREAD

**Issue by c1bles** [NoCrypt/migu#16]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

I would like MAL to be added, because the original author of miru said its gonna take 6+ months to be added by a contributor, i have low hopes. plz if you can add it, because i switched from anilist to MAL a while back because of server issues and more. And i don't want to switch back to anilist.

### Proposed Solution

i don't have any 😭

**Comment by NoCrypt** [comment]
Done 5a7d2ad5051089c43b783d81d7e12c6791c44516
