### ISSUE TITLE
[Feature Request]: Toggle for enabling/disabling swipe controls

### ISSUE THREAD

**Issue by honny78** [NoCrypt/migu#17]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

Swipe controls

### Proposed Solution

Add toggle for enabling/disabling swipe controls, something you can hit them by accident

**Comment by NoCrypt** [comment]
Done https://github.com/NoCrypt/migu/commit/6e6aef7de8d948fbd0c35e19c9059cfadc9615b1
