### ISSUE TITLE
[Feature Request]: Add support for AC3 and E-AC3 audio

### ISSUE THREAD

**Issue by ISatoruGit** [NoCrypt/migu#18]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

Audio codec not supported.

![image](https://github.com/user-attachments/assets/d3ecafca-7271-4b80-8960-73c308e9b360)

### Proposed Solution

Please consider adding support for those codecs as they are widely used in releases sourced from AMZN, NF, MAX and some DVDs, so it'd be good to properly support them.

You may find that helpful:
https://github.com/ThaUnknown/electron-chromium-codecs

**Comment by NoCrypt** [comment]
Nice find
