### ISSUE TITLE
[Feature Request]: iOS App?

### ISSUE THREAD

**Issue by iPixelGalaxy** [NoCrypt/migu#19]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

Lack of iOS version.

### Proposed Solution

Would it be possible to get an iOS .ipa release as well since you can technically sideload those even with a free account using something like Sideloadly or AltStore? Since there is already a mac version I can't imagine it would be too tough to adapt that?

**Comment by NoCrypt** [comment]
It is tough. The capacitor NodeJS plugin we're using [didn't support iOS](https://github.com/hampoelz/Capacitor-NodeJS#:~:text=Android-,IOS%20(coming%20soon),-Using%20the%20capacitor) yet as of now. Even though, we already have NodeJS mobile for iOS, we have to wait the maintainer for said plugin to supports it.

**Comment by iPixelGalaxy** [comment]
Ahh, that makes sense then!
