### ISSUE TITLE
[Feature Request]: Playback speed

### ISSUE THREAD

**Issue by blindmodz** [NoCrypt/migu#20]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

I'm really used to watch anime on 1.2x or even 1.5x and can't do it on the default player without using an external media player and losing the auto update on AniList.

### Proposed Solution

Just add a playback speed button for the in app media player

**Comment by NoCrypt** [comment]
Done edf6057d77ec513f504ceabb91f41b70e17d3797
