### ISSUE TITLE
Black screen with in-app media player

### ISSUE THREAD

**Issue by blindmodz** [NoCrypt/migu#30]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

V5.6.1

### What operating system version are you using?

Android

### Expected Behavior

The screen shows the video. 

### Actual Behavior

In-app player was working fine and after using external player and going back to the in-app player, the entire screen is black while the audio is playing, tried reinstalling/wiping data but still showing blackscreen while audio is playing.
My external player was Next and selected it as default.
[phone.txt](https://github.com/user-attachments/files/17051946/phone.txt)
info of my phone and settings

**Comment by Guru237** [comment]
Whole app works fine except player it needs lots of improvement RN use external player

**Comment by NoCrypt** [comment]
Usually it was the connection issue, can you recheck if your connection was okay or not?
I dont have loading screen for player yet since I hide them for "Hide Miniplayer" feature

**Comment by blindmodz** [comment]
I think it's related to lack of some video codes on my phone so nothing to do :/

**Comment by NoCrypt** [comment]
You can use extenal player option for the moment
