### ISSUE TITLE
[Bug]: Update to MyAnimeList does not change anime status to Complete once finished

### ISSUE THREAD

**Issue by cf-h** [NoCrypt/migu#32]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

5.6.1

### What operating system version are you using?

MacOS

### Expected Behavior

After finishing the final episode of the anime, the status should change from "Watching" into "Completed"

### Actual Behavior

Currently only the last watched episode is updated by the status is still kept as "Watching"

**Comment by NoCrypt** [comment]
83e4d30d250932f0ee167a823b3c8130409c22ba
