### ISSUE TITLE
[Bug]: failed to load media for home feed. And can't find torrent for any anime 

### ISSUE THREAD

**Issue by SahilBulatoo** [NoCrypt/migu#34]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

V5.6.1

### What operating system version are you using?

Android

### Actual Behavior

Nothing in new release is loading cannot find any torrent for any anime. 
![Screenshot_2024-09-21-21-20-13-38_f999c2803d73b9e7183ead2b66d87835](https://github.com/user-attachments/assets/ebeef4c3-582d-4fd7-8bfd-e00d45029602)
![Screenshot_2024-09-21-21-20-26-77_f999c2803d73b9e7183ead2b66d87835](https://github.com/user-attachments/assets/d05f8a9f-0d30-487a-9710-eb4ca3432e94)

**Comment by SahilBulatoo** [comment]
Expected behavior should have been that it shows new episode of animes. And search for different torrents when u select an episode to watch

**Comment by blindmodz** [comment]
> Expected behavior should have been that it shows new episode of animes. And search for different torrents when u select an episode to watch

animetosho is down (maintenance iirc), need to find a new fetch
