### ISSUE TITLE
[Bug]: Seadex does not function

### ISSUE THREAD

**Issue by Cszyn** [NoCrypt/migu#4]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

v5.3.1

### What operating system version are you using?

Android

### Expected Behavior

Loads the list of available torrents.

### Actual Behavior

Does not load, gives an error(s).

Android 14 HyprOS v1
Android 12 Mumu player

### Screenshots

![MuMuPlayer_j7qaKc9kRZ](https://github.com/user-attachments/assets/9a00428f-9ca6-4f41-be26-02ef521ddced)

**Comment by NoCrypt** [comment]
Works fine here, I guess your ISP blocking that site?

**Comment by Cszyn** [comment]
Its does not. normal miru on pc has it working correctly

**Comment by Cszyn** [comment]
https://github.com/NoCrypt/migu/issues/5#issuecomment-2298938653

I posted a comparison in that

**Comment by yoinked-h** [comment]
can confirm here too, not that big of an issue, still lets me use the other reccomended torrent

**Comment by NoCrypt** [comment]
Turns out this is a CORS issue, I cant seems to find the reason why, but it doesnt affect the experience that much so I suggest to just disable SeaDex from the Source Settings

**Comment by systematicequation** [comment]
Modifying the extension under Torrent settings from `@thaunknown/ani-resourced` to `anisearch` (same NPM package with same owner but more up-to-date) appears to fix this issue for me.

The URL for the SeaDex source was changed in order to resolve the issue.

**Comment by Cszyn** [comment]
> Modifying the extension under Torrent settings from `@thaunknown/ani-resourced` to `anisearch` (same NPM package with same owner but more up-to-date) appears to fix this issue for me.
> 
> The URL for the SeaDex source was changed in order to resolve the issue.

So like @thaunknown/anisearch ?

**Comment by systematicequation** [comment]
> > Modifying the extension under Torrent settings from `@thaunknown/ani-resourced` to `anisearch` (same NPM package with same owner but more up-to-date) appears to fix this issue for me.
> > The URL for the SeaDex source was changed in order to resolve the issue.
> 
> So like @thaunknown/anisearch ?

Just `anisearch`.

**Comment by Cszyn** [comment]
Ah I see. Yes that does appear to fix it

**Comment by NoCrypt** [comment]
Fixed
https://github.com/NoCrypt/migu/commit/3ef10df57ddfba8f0faa52c4ebfff9efff2bcd63
