### ISSUE TITLE
[Feature Request]: F-droid

### ISSUE THREAD

**Issue by Hexality** [NoCrypt/migu#40]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

Github can be confusing for some people.

### Proposed Solution

Would it be possible to add it to something like F-Droid with a small tutorial on the readme?

**Comment by NoCrypt** [comment]
It's been on izzyondroid for a while now
https://apt.izzysoft.de/fdroid/index/apk/watch.migu
