### ISSUE TITLE
[Feature Request]: Refresh option

### ISSUE THREAD

**Issue by Eksided** [NoCrypt/migu#41]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

I use an external player and taiga to watch anime in bulk at the same time, when I'm like 5+ episodes ahead I at times forget what episode I watched at last and Migu doesn't refresh the anilist tracking, I even forgot to open taiga once so didn't know on which episode I left on.

Also on a separate note I leave Migu open for extensive periods of times in the background so when there's a new anime it doesn't pop up on "New releases" so I have to reopen Migu to show if anything new released, same issue if I'm waiting for an anime to release so I find out what happens next, basically refreshing every 30 seconds to see if it's out.

### Proposed Solution

Refresh button or F5 as shortcut to refresh feed.

**Comment by NoCrypt** [comment]
`Ctrl`+`R` works
