### ISSUE TITLE
[Bug]: Feed is broken from GitHub apk

### ISSUE THREAD

**Issue by Cszyn** [NoCrypt/migu#5]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

v5.3.1

### What operating system version are you using?

Android

### Expected Behavior

Feed loads

### Actual Behavior

Feed doesn't load, gives JS error.

Android 12 - Mumu Emulator

### Screenshots

![MuMuPlayer_Lmk7EHkpBe](https://github.com/user-attachments/assets/5e6c0f2f-d834-49ca-a1a0-2ebcf0a2461a)

**Comment by NoCrypt** [comment]
Works fine here, I guess your ISP blocking that site?

**Comment by Cszyn** [comment]
I have updated to 5.3.7, but the issue is still here. I also downloaded migu to my pc to test if it's broken with that, but it's an android exclusive.
![Migu_sAJKzmtvq2](https://github.com/user-attachments/assets/58afcd69-5e9d-4b9b-ab6a-d72a948a3d4b)
![scrcpy_akXaJHtYhK](https://github.com/user-attachments/assets/f833cb27-fa30-4234-a830-e11608107ba5)
![scrcpy_WdHHBHTzcz](https://github.com/user-attachments/assets/a676cf94-88bf-4c05-9d07-3b49451b178c)
![scrcpy_mxmF0bVQMs](https://github.com/user-attachments/assets/f7df1c0d-01fc-46f6-83c1-5a4566eed8ff)

**Comment by NoCrypt** [comment]
Could also be caused by AniList server not responding

**Comment by Cszyn** [comment]
For now I'll blame the emulator and close this issue as the app works fine on my primary devices
