### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ragatokk** [NoCrypt/migu#59]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

v5.6.2

### What operating system version are you using?

Windows

### Expected Behavior

Load start screen
Worked well previously.

### Actual Behavior

Seems like connection issues of some kind?

### Screenshots

![image](https://github.com/user-attachments/assets/034b4723-f3f5-4df2-9ff8-c58f8597eb99)

**Comment by Ragatokk** [comment]
My apologies for making a ironious bug report here, I did not realize it was an anilist issue until I looked at my own screenshot here.
![image](https://github.com/user-attachments/assets/0fe14b51-7dd0-4334-bd5d-68f52fc42084)

**Comment by Ragatokk** [comment]
Closed the issue as I believe it's not something to fix on your end, just wanted to make you aware if you were not.

**Comment by injusticedevil** [comment]
So whats the solution for this
