### ISSUE TITLE
[Feature Request]: Chat for Watch Party

### ISSUE THREAD

**Issue by TunayAdaKaracan** [NoCrypt/migu#6]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

There is no chat feature in the app. This is not an exactly problem as another third party app could be used but for android it is hard to use both at same time.

### Proposed Solution

 You could make a chat button that opens up a chat on the right side of the screen. It does not need to be fancy. A simple one would be enough for a lot of people.

**Comment by NoCrypt** [comment]
Planned on future Miru release, check their discord server for more info.
![image](https://github.com/user-attachments/assets/4e5d9850-4692-41a2-b658-7fbc179380b1)

**Comment by NoCrypt** [comment]
Fixed
https://github.com/NoCrypt/migu/commit/cb1c591b177ef2ace85ae33342e991d3acada85a
