### ISSUE TITLE
[Feature Request]: Add a download button

### ISSUE THREAD

**Issue by Cszyn** [NoCrypt/migu#7]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

I have a limited data plan with 10gb/Mo but a phone with 500gb of storage, so I download a lot of media for offline viewing during travel or commutes, which I do a lot of.

### Proposed Solution

Adding a download button next to the available torrents when clicking on an episode, or similar.

**Comment by NoCrypt** [comment]
Not exactly download button, but you can enable Persist File and Change the Download folder from the settings on v5.3.8

https://github.com/NoCrypt/migu/commit/867d86c35313894006d0a1f796c0af5662948664
