### ISSUE TITLE
[Feature Request]: Implement audio track switching into the android player

### ISSUE THREAD

**Issue by Cszyn** [NoCrypt/migu#9]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

I'm a dub guy. I prefer to check out dubs first and if they're bad I'll watch in JP/Subs. **The app does not respect my language settings. I have it set to English dub English Sub, but even when the stream is dual audio, I still get the JP audio track played with no way to change it to English.**

### Proposed Solution

Implement the audio track switch button from desktop and potentially address the issue with the settings being disregarded.

**Comment by NoCrypt** [comment]
Android WebView didn't support `audioTracks` feature yet, for now your solution is to use External Player to stream anime with Dual-Audio
